### ISSUE TITLE
Error: Use CoffeeScript.register() or require.... why?

### ISSUE THREAD

**Issue by ziippy** [ffissore/connect-orientdb#6]
I was run the connect-orientdb on my Node server using npm
And. my test.js code is like below

> var express = require('express');
> var app = express();
> var OrientDBStore = require('connect-orientdb')(express);
> var settings = {
>     server: {
>         host: "localhost",
>         port: 2424
>     },
>     db: {
>         user_name: "root",
>         user_password: "111111"
>     },
>     database: "mydb",
>     class_name: "Session"
> };
> app.use(session({
>   resave: false
>   , saveUninitialized: true
>   , secret: settings.cookie_secret
>   , store: new OrientDBStore(settings)
> }));
> app.get('/', function (req, res) {
>   res.send('Hello World!');
> });
> app.listen(3000, function () {
>   console.log('Example app listening on port 3000!');
> });

after then, i try to run "node test.js"

But, the result's like below

> D:\nodejs\dev\myapp\node_modules\coffee-script\lib\coffee-script\coffee-script.js:
> 213  
>           throw new Error("Use CoffeeScript.register() or require the coffee-script/register module 
> to require " + ext + " files."); 
> Error: Use CoffeeScript.register() or require the coffee-script/register module to require .coffee.m
> d files.  
>   at Object.base.(anonymous function) [as .coffee](D:2016_Working_etcnodejsdevmyappnode_modul
> escoffee-scriptlibcoffee-scriptcoffee-script.js:213:17)  
>   at Module.load (module.js:343:32)  
>   at Function.Module._load (module.js:300:12)

What's wrong?

I already install the coffee-script module

**Comment by viktor-gusev** [comment]
Has same issue. Found another repo:
https://github.com/ventu-io/connect-oriento
Works fine for me.

**Comment by ffissore** [comment]
Just be aware that oriento is not the official nodejs driver for orientdb. However, a session store for OrientDB based on https://github.com/orientechnologies/orientjs is curently missing /cc @maggiolo00
